Don't use go modules for licenseclassifier.
I think this is causing the current presubmit error:
  Error: cannot register licenses from archive: open /home/prow/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20190926221455-842c0d70d702/licenses/licenses.db: no such file or directory

This was changed to use modules in https://github.com/tektoncd/plumbing/commit/fb80e6b4c5b88032c8cf6eadcf04d4b9532ac076

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>