Add `-f` to cleanup's `tkn ... delete` calls
Because the `TaskRun`s are currently failing like:

```
Defaulted container "step-cleanup-pr-tr" out of: step-cleanup-pr-tr, prepare (init), place-scripts (init)
+ '[[' 200 -eq 0 -o 200 '=='  ]]
+ tkn pr delete -n default --keep 200
Error: json: cannot unmarshal object into Go value of type []string
Are you sure you want to delete all PipelineRuns in namespace "default" keeping 200 PipelineRuns (y/n): %
```

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>